# Generated by Django 5.0 on 2025-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.PositiveIntegerField(default=7, help_text='Number of days allowed for payment'),
        ),
    ]
