# Generated by Django 5.0 on 2025-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_created_by_role_order_location_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location_country',
        ),
        migrations.AddField(
            model_name='order',
            name='location_city_district',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='location_display_name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
