# Generated by Django 5.0 on 2025-01-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_location_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='location_city_district',
        ),
    ]
