services:
  - type: web
    name: phani-react-backend
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn backend.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: phani-react-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  - type: web
    name: phani-react-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview"
    envVars:
      - key: VITE_API_URL
        value: "https://phani-react-backend.onrender.com"

databases:
  - name: phani-react-db
    databaseName: phani_react
    user: phani_react
    plan: free 