# Generated by Django 5.0 on 2025-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('BLOCKED', 'Blocked')], default='PENDING', max_length=10),
        ),
    ]
